# Generated by Django 4.0.2 on 2022-03-10 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_album', models.CharField(max_length=100)),
                ('foto_capa_album', models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/')),
                ('local_album', models.CharField(max_length=100)),
                ('data_album', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, upload_to='album/%m/%Y/')),
                ('id_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.album')),
            ],
        ),
    ]
