# Generated by Django 4.0.2 on 2022-03-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='exibir_album',
            field=models.BooleanField(default=True),
        ),
    ]
