# Generated by Django 4.0.2 on 2022-03-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_album_exibir_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_destaque',
            field=models.BooleanField(default=True),
        ),
    ]
