# Generated by Django 4.0.2 on 2022-03-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/')),
                ('banner_ativo', models.BooleanField(default=False)),
            ],
        ),
    ]
