# Generated by Django 4.0.2 on 2022-03-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integrantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_integrante', models.CharField(max_length=100)),
                ('foto_integrante', models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/')),
                ('data_entrada', models.DateTimeField()),
                ('data_saida', models.DateTimeField(blank=True)),
                ('integrante_ativo', models.BooleanField(default=True)),
                ('cargo_integrante', models.CharField(choices=[('PRE', 'Presidente'), ('VIC', 'Vice-Presidente'), ('DIR', 'Diretor'), ('INT', 'Integrante'), ('ESP', 'Espelho'), ('PRO', 'Prospero')], default='INT', max_length=3)),
            ],
        ),
    ]
