# Generated by Django 4.0.2 on 2022-03-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrantes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrantes',
            name='data_saida',
        ),
    ]
