# Generated by Django 4.0.2 on 2022-03-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrantes', '0003_alter_integrantes_cargo_integrante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrantes',
            name='cargo_integrante',
            field=models.CharField(choices=[('1-PRE', 'Presidente'), ('3-VIC', 'Vice-Presidente'), ('5-DIR', 'Diretor'), ('2-INT', 'Integrante'), ('4-PRO', 'Prospero'), ('6-ESP', 'Espelho')], default='4-INT', max_length=5),
        ),
    ]
